version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - nilerr
    - errorlint
    - gocritic
    - wastedassign
  disable:
    - errcheck
    - noctx

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
  revive:
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
        disabled: true
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: error
      - name: error-return
        severity: error
      - name: error-naming
        severity: error

issues:
  exclude-rules:
    - path: internal/crypto/crypto\.go
      linters:
        - unused
    - path: internal/fileapi/service\.go
      linters:
        - unused
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true